# Настройки подключения к базе данных PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/имя_вашей_бд
    username: ваше_имя_пользователя
    password: ваш_пароль
    driver-class-name: org.postgresql.Driver

  # Настройки Hibernate для JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

# Настройки логирования SQL запросов
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
  file: logs/app.log # Путь к файлу логов
